

title: Christian Dimitri
subtitle: Architect & Computational Designer
logo: assets/img/dimi-white.png

paginate: 2
paginate_path: "/blog/page:num/"

gem 'github-pages', '170', group: :jekyll_plugins

plugins: [
  jekyll-paginate
]
